config/routes.rb
Rails.application.routes.draw do
  resources :notification_posts
  # =========================
  # Root
  # =========================
  root to: 'static_pages#index'

  # =========================
  # Devise
  # =========================
  devise_for :users, path: '', path_names: {
      sign_in: 'ingreso', sign_up: 'registro'
  }, controllers: {
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
  }

  devise_for :administrators, path: '', path_names: {
      sign_in: 'ingreso_admin'
  }
  # =========================
  # Resources
  # =========================
  resources :administrators do
    collection do
      get 'opportunities'
      get 'pending_opportunities'
      post 'download_excel'
    end
  end

  resources :companies, only: [:show, :index]
  resources :people, only: [:show, :index]
  resources :students, only: [:show, :index] do
    member do
      post 'delete_second_major'
    end
  end

  resources :users, except: [:new, :create, :show] do
    member do
      post 'build_learnt_language'
      post 'mark_as_selected'
      post 'rate_opportunity'
    end
  end

  resources :opportunities do
    member do
      get 'application_form'
      post 'apply'
      get 'applicants'
      post 'approve'
      post 'close'
      post 'acquire_information'
    end
    collection do
      get 'my_opportunities'
    end
  end

  # =========================
  # Controllers
  # =========================
  # get '/about', to: 'static_pages#about'
  get '/admin_panel', to: 'administrators#index'
  get '/company_pricing', to: 'static_pages#pricing'
  # get "/payment_page", :to => "companies#payment_page", :as => "payment_page"
  get "/payment_response_page", :to => "companies#payment_response_page", :as => "payment_response_page"
  post "/payment_confirmation_page", :to => "companies#payment_confirmation_page", :as => "payment_confirmation_page"

  # ============
  # Mailer
  # ============
  # match '/contacto', to: 'Contacts#new', via: :get
  # match '/contacto', to: 'Contacts#create', via: :post
end

app/models/notification_post.rb
 # == Schema Information
#
# Table name: notification_posts
#
#  id         :integer          not null, primary key
#  name       :string
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_notification_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class NotificationPost < ApplicationRecord
  belongs_to :user
end

app/controllers/notification_posts_controller.rb
 class NotificationPostsController < ApplicationController
  before_action :set_notification_post, only: [:show, :edit, :update, :destroy]

  # GET /notification_posts
  # GET /notification_posts.json
  def index
    @notification_posts = NotificationPost.all.page params[:page]
    @notification_post = NotificationPost.new 
     @notification_post.user_id = current_administrator.id if current_administrator
     @notification_post.user_id = current_user.id if current_user
  end

  # GET /notification_posts/1
  # GET /notification_posts/1.json
  def show
  end

  # GET /notification_posts/new
  def new
    @notification_post = NotificationPost.new 
     @notification_post.user_id = current_administrator.id if current_administrator
     @notification_post.user_id = current_user.id if current_user
  end

  # GET /notification_posts/1/edit
  def edit
  end

  # POST /notification_posts
  # POST /notification_posts.json
  def create
    @notification_post = NotificationPost.new(notification_post_params)

    respond_to do |format|
      if @notification_post.save
        format.html { redirect_to @notification_post, notice: 'Se ha publicado exitosamente tu notificación' }
        format.json { render :show, status: :created, location: @notification_post }
      else
        format.html { render :new }
        format.json { render json: @notification_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notification_posts/1
  # PATCH/PUT /notification_posts/1.json
  def update
    respond_to do |format|
      if @notification_post.update(notification_post_params)
        format.html { redirect_to @notification_post, notice: 'Notification post was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification_post }
      else
        format.html { render :edit }
        format.json { render json: @notification_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notification_posts/1
  # DELETE /notification_posts/1.json
  def destroy
    @notification_post.destroy
    respond_to do |format|
      format.html { redirect_to notification_posts_url, notice: 'Notification post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification_post
      @notification_post = NotificationPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_post_params
      params.require(:notification_post).permit(:name, :body, :user_id)
    end
end

app/helpers/notification_posts_helper.rb
 module NotificationPostsHelper
end

app/views/notification_posts/_edit.html.erb
 <div class="modal fade" id="notificationModal" tabindex="-1" role="dialog" aria-labelledby="notificationModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="loginmodal-container">
      <h1>Create Notification</h1>
      <%= render 'form', notification_post: @notification_post %>
    </div>
  </div>
</div>

app/views/notification_posts/_form.html.erb
 <%= form_with(model: notification_post, local: true) do |form| %>
    <%= render partial: 'shared/error_messages', locals: { object: @notification_post } %>

    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= form.label :nombre %>
           <%= form.text_field :name, id: :notification_post_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :cuerpo %>
          <%= form.text_area :body, id: :notification_post_body , class: 'form-control' %>
        </div>
        </div>
</div>
        
    <div class="row">
      <div class="col-md-12 text-center">
       <%= form.hidden_field :user_id, id: :notification_post_user_id %>
        <div class="actions">
           <%= form.submit 'Crear Notificación', class: 'btn btn-primary btn-studnet-basic' %>
        </div>
      </div>
    </div>

<% end %>

app/views/notification_posts/_new.html.erb
 <div class="modal fade" id="notificationModal" tabindex="-1" role="dialog" aria-labelledby="notificationModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="loginmodal-container">
      <h1>Nueva  Notificación</h1>
      <%= render 'form', notification_post: @notification_post %>
    </div>
  </div>
</div>

app/views/notification_posts/edit.js.erb
 $('.new-modal').html("<%= j render 'edit' %>");
$('#notificationModal').modal('show');

app/views/notification_posts/new.js.erb
 $('.new-modal').html("<%= j render 'new' %>");
$('#notificationModal').modal('show');

app/views/notification_posts/show.html.erb
 <section class="devise-wrapper">
  <div class="companies-signup-header notification-comapny-header margin-bot-40">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>
            Notificaciones de la empresa

          </p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="studNet-wrapper student-tab-wrapper padding-bot-40">
  <div class="container">

    <div class="row">
      <div class="col-md-10 col-md-offset-1 student-tab-content company-tab-content">

        <!-- Company Info -->
        <div class="row">
          <!-- Contact Info -->
          <div class="col-md-6">
            <h3>
              Detalle
             </h3>

            <table class="table studNet-table">
              <tbody>

              <tr>
                <td>
                  <strong>Nombre:</strong>
                </td>
                <td>
                  <%= @notification_post.name %>
                </td>
              </tr>

              <tr>
                <td>
                  <strong>Cuerpo:</strong>
                </td>
                <td>
                  <%= @notification_post.body %>
                </td>
              </tr>

              <tr>
                <td>
                 <strong>Usuario:</strong>
                </td>
                <td>
                  <%= @notification_post.user.first_name %>
                </td>
              </tr>

              </tbody>
            </table>

          </div>
          <!-- Company Info -->
        </div>
        <!-- ./Company Info -->
      </div>
    </div>

    <% if user_signed_in? %>
        <!-- Actions -->
        <div class="row">
          <div class="col-md-12 student-actions-wrapper text-center">
         
            <%#= link_to 'Editar perfil', edit_notification_post_path(@notification_post) , class: 'btn btn-primary btn-studnet-basic' %>

           
                 <%= link_to 'Editar notificación', edit_notification_post_path(@notification_post), remote: true %> 
       
          </div>
        </div>
        <!-- ./Actions-->
    <% end %>

  </div>
</section>
<div class="new-modal"></div>