config/routes.rb
Rails.application.routes.draw do
  resources :notification_posts
  # =========================
  # Root
  # =========================
  root to: 'static_pages#index'

  # =========================
  # Devise
  # =========================
  devise_for :users, path: '', path_names: {
      sign_in: 'ingreso', sign_up: 'registro'
  }, controllers: {
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
  }

  devise_for :administrators, path: '', path_names: {
      sign_in: 'ingreso_admin'
  }
  # =========================
  # Resources
  # =========================
  resources :administrators do
    collection do
      get 'opportunities'
      get 'pending_opportunities'
      post 'download_excel'
    end
  end

  resources :companies, only: [:show, :index]
  resources :people, only: [:show, :index]
  resources :students, only: [:show, :index] do
    member do
      post 'delete_second_major'
    end
  end

  resources :users, except: [:new, :create, :show] do
    member do
      post 'build_learnt_language'
      post 'mark_as_selected'
      post 'rate_opportunity'
    end
  end

  resources :opportunities do
    member do
      get 'application_form'
      post 'apply'
      get 'applicants'
      post 'approve'
      post 'close'
      post 'acquire_information'
    end
    collection do
      get 'my_opportunities'
    end
  end

  # =========================
  # Controllers
  # =========================
  # get '/about', to: 'static_pages#about'
  get '/admin_panel', to: 'administrators#index'
  get '/company_pricing', to: 'static_pages#pricing'
  # get "/payment_page", :to => "companies#payment_page", :as => "payment_page"
  get "/payment_response_page", :to => "companies#payment_response_page", :as => "payment_response_page"
  post "/payment_confirmation_page", :to => "companies#payment_confirmation_page", :as => "payment_confirmation_page"

  # ============
  # Mailer
  # ============
  # match '/contacto', to: 'Contacts#new', via: :get
  # match '/contacto', to: 'Contacts#create', via: :post
end

app/models/administrator.rb
 # == Schema Information
#
# Table name: administrators
#
#  id                     :integer          not null, primary key
#  name                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#
# Indexes
#
#  index_administrators_on_email                 (email) UNIQUE
#  index_administrators_on_reset_password_token  (reset_password_token) UNIQUE
#

class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:recoverable, :rememberable, :trackable, :validatable
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  include AdministratorsHelper

  before_action :set_administrator, only: [:show, :edit, :update, :destroy]

  def index
    @administrators = Administrator.all
  end

  def show
  end

  def new
    @administrator = Administrator.new
  end

  def edit
  end

  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save

        flash[:success] = 'El administrador fue creado exitosamente.'
        format.html { redirect_to @administrator }
      else
        flash[:error] = 'El administrador no pudo ser creado, por favor intentarlo nuevamente.'
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        flash[:success] = 'El administrador fue actualizado exitosamente.'
        format.html { redirect_to @administrator }
      else
        flash[:error] = 'El administrador no pudo ser actualizado, por favor intentarlo nuevamente.'
        format.html { render :edit }
      end
    end
  end

  def destroy
    @administrator.destroy
    respond_to do |format|
      flash[:success] = 'El administrador fue eliminada exitosamente.'
      format.html { redirect_to administrators_url }
    end
  end

  def download_excel
    if Rails.env.development?
      path = get_user_excel_path
      send_file path
    else
      Thread.new do
        path = get_user_excel_path
        AdministratorMailer.users_excel(path).deliver_now
      end.run
      session[:excel] = true
      redirect_to opportunities_administrators_path
    end
  end

  #===================
  # Custom actions
  #===================

  def opportunities
    @opportunities = Opportunity.all
    @stats = {
        students: User.all_by_role(User::ROLE_STUDENT).count,
        people: User.all_by_role(User::ROLE_PERSON).count,
        companies: User.all_by_role(User::ROLE_COMPANY).count,
        active_offers: Opportunity.approved.count
    }
  end

  def pending_opportunities
    @opportunities = Opportunity.pending_approval
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_administrator
    @administrator = Administrator.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def administrator_params
    params.require(:administrator).permit(:name)
  end
end

app/helpers/administrators_helper.rb
 module AdministratorsHelper

  def get_user_excel_path
    file_path = new_excel_file_path
    excel = Axlsx::Package.new

    excel.workbook.add_worksheet(name: 'Estudiantes') do |sheet|
      sheet.add_row USER_HEADER_ROWS + STUDENT_HEADER_ROWS
      sheet.add_row USER_ROWS + STUDENT_ROWS

      students = User.all_by_role User::ROLE_STUDENT
      students.each do |student|
        write_row_for_student student, sheet
      end
    end

    excel.workbook.add_worksheet(name: 'Empresas') do |sheet|
      sheet.add_row USER_HEADER_ROWS + COMPANY_HEADER_ROWS
      sheet.add_row USER_ROWS + COMPANY_ROWS

      companies = User.all_by_role User::ROLE_COMPANY
      companies.each do |company|
        write_row_for_company company, sheet
      end
    end

    excel.workbook.add_worksheet(name: 'Personas') do |sheet|
      sheet.add_row USER_HEADER_ROWS + PERSON_HEADER_ROWS
      sheet.add_row USER_ROWS + PERSON_ROW

      people = User.all_by_role User::ROLE_PERSON
      people.each do |person|
        write_row_for_person person, sheet
      end
    end

    excel.workbook.add_worksheet(name: 'Oportunidades') do |sheet|
      sheet.add_row OPPORTUNITY_HEADER_ROWS
      sheet.add_row OPPORTUNITY_ROWS

      Opportunity.all.each do |opportunity|
        write_row_for_opportunity opportunity, sheet
      end
    end

    excel.serialize file_path
    file_path
  end

  private
  USER_HEADER_ROWS = ['Email de tu cuenta', 'Nombre(s)', 'Apellidos', 'Edad', 'País', 'Ciudad en la que vives', 'Otra', 'Teléfono celular', 'Documento de identidad', '¿Cómo te enteraste de studNet?', 'Código promocional (no obligatorio)']
  USER_ROWS = %w(email first_name last_name date_of_birth country city other_city mobile_phone document_number referenced_by promo_id)

  # Student
  STUDENT_HEADER_ROWS = ['Universidad', 'Carrera', 'Nivel', 'Universidad segunda carrera', 'Segunda carrera', 'Nivel segunda carrera', 'Otra universidad', 'Otra carrera', 'Otras carreras', 'Último semestre cursado', 'Calificación máxima en tu universidad', 'Promedio académico acumulado', 'Tipo de estudiante', '¿Has realizado algún intercambio académico?', 'Indica el país en el cual realizaste el intercambio', 'Indica el nombre de la universidad en la cual realizaste el intercambio', 'Indica el nombre del colegio del que te graduaste', '¿Tienes experiencia laboral?', 'Indica el nombre de la empresa en la que trabajaste', 'Indica el nombre de tu cargo en la empresa', 'Indica tus principales funciones y logros en el cargo', 'Indica el nombre de la empresa en la que trabajaste 2', 'Indica el nombre de tu cargo en la empresa 2', 'Indica tus principales funciones y logros en el cargo 2', 'Indica el nombre de la empresa en la que trabajaste 3', 'Indica el nombre de tu cargo en la empresa 3', 'Indica tus principales funciones y logros en el cargo 3', '¿Realizas o has realizado una actividad social / de voluntariado?', 'Indica el nombre de la organización donde realizaste esta actividad', 'Indica tus funciones en esta organización', 'Indica el nombre de la organización donde realizaste esta actividad 2', 'Indica tus funciones en esta organización 2', 'Indica el nombre de la organización donde realizaste esta actividad 3', 'Indica tus funciones en esta organización 3', 'Idiomas', 'Herramientas', '¿Qué otras herramientas sabes manejar / qué otras habilidades tienes?', '¿Sabes programar?', 'Por favor indica en qué lenguajes sabes programar', '¿Cuáles son tus principales fortalezas?', '¿En qué áreas te gustaría desarrollar tu carrera profesional?', 'Describe brevemente tus intereses, tus hobbies y demás información que describa quien eres']
  STUDENT_ROWS = %w(university_name major_name level_name second_university_name second_major_name second_level_name other_university other_major other_majors last_semester gpa_max gpa type_of_student exchange_student exchange_country exchange_university highschool work_xp xp_company xp_position xp_achievements second_xp_company second_xp_position second_xp_achievements third_xp_company third_xp_position third_xp_achievements volunteer_xp volunteer_org volunteer_functions second_volunteer_org second_volunteer_functions third_volunteer_org third_volunteer_functions learnt_languages tools other_tools_skills programming_skills programing_languages strengths areas_to_develop hobbies)

  STUDENT_TO_SINGLE_RELATIONS = { 'university_name' => 'university', 'major_name' => 'major', 'level_name' => 'education_level', 'second_university_name' => 'second_university', 'second_major_name' => 'second_major', 'second_level_name' => 'second_education_level', 'exchange_country' => 'country' }
  STUDENT_TO_MANY_RELATIONS = { 'other_majors' => 'majors',  'tools' => 'tools', 'learnt_languages' => 'learnt_languages' }

  # Company
  COMPANY_HEADER_ROWS = ['Nombre de la empresa', 'NIT', 'Breve descripción de tu empresa', 'Sector', 'Tamaño', 'Página web', 'Cargo', 'Dirección']
  COMPANY_ROWS = %w(company_name company_nit company_description sector_name company_size company_website_url position company_address)

  COMPANY_TO_SINGLE_RELATIONS = { 'sector_name' => 'sector' }

  # Person
  PERSON_HEADER_ROWS = ['Ocupación',	'Profesión / Carrera']
  PERSON_ROW = %w(occupation	profession)

  # Opportunities
  OPPORTUNITY_HEADER_ROWS = ['Email de tu cuenta:', 'Tipo de ususario:', 'Nombre de la empresa: / Nombre (completo) de la persona:', 'Tipo de oferta', 'Título de la oferta', 'Descripción de las actividades a realizar', 'Descripción de las habilidades y conocimientos requeridos', '¿Permitir aplicaciones de todas las carreras?', '¿De qué carreras buscas los estudiantes?', 'Pregunta al estudiante', 'Fecha de cierre de la convocatoria (Antes: fecha de inicio del trabajo / proyecto)', 'Fijar fechas', 'Duración del trabajo / proyecto', 'Duración del trabajo (en días, semanas o meses)', 'Tiempo requerido del estudiante', '¿Quieres poner un valor para el proyecto o escuchar ofertas de los estudiantes?', 'Salario / valor del proyecto', '¿Quieres recibir el portafolio de los estudiantes que apliquen a tu oferta? (Para ofertas de artes, diseño, arquitectura y afines)', '¿Cuántos estudiantes necesitas para esta oferta?', 'Número de aplicaciones', 'Correos de aplicantes', 'Estado de la oferta', 'Candidatos seleccionados']
  OPPORTUNITY_ROWS = %w(email role_type company_person_name opportunity_type_description opportunity_title activity_description skills_description other_majors majors question_for_student date_ini_type_friendly date_ini duration_type_description opportunity_duration availability_description cost_or_offer_description opportunity_cost receive_portfolio number_of_students number_of_applicants	applicants_emails	approved_state selected_applicant_emails)

  OPPORTUNITY_TO_MANY_RELATIONS = %w(majors)

  def new_excel_file_path
    file_name = "users-#{Time.now.strftime '%d-%m-%Y-%H_%M'}.xlsx"
    Pathname.new(Dir.tmpdir).join file_name
  end

  def write_row_for_student(user, sheet)
    row = []
    student = user.student

    write_rows_for_user user, row

    STUDENT_ROWS.each do |attribute|
      if STUDENT_TO_SINGLE_RELATIONS.keys.include? attribute
        if student.send(STUDENT_TO_SINGLE_RELATIONS[attribute]).nil?
          row << nil
        else
          row << student.send(STUDENT_TO_SINGLE_RELATIONS[attribute]).name
        end
      elsif STUDENT_TO_MANY_RELATIONS.keys.include? attribute
        temp_row = []

        if attribute.eql? 'learnt_languages'
          student.send(STUDENT_TO_MANY_RELATIONS[attribute]).each do |learnt_language|
            if !learnt_language.language.nil? && !learnt_language.language_level.nil?
              temp_row << "#{learnt_language.language.name} (#{learnt_language.language_level})"
            end
          end
        else
          student.send(STUDENT_TO_MANY_RELATIONS[attribute]).each do |model|
            temp_row << model.name
          end
        end

        row << (temp_row.empty? ? nil : temp_row.join(','))
      else
        if attribute.eql? 'type_of_student'
          row << student.friendly_type_of_student
        else
          row << (student[attribute].to_s.blank? ? nil : student[attribute])
        end
      end
    end

    sheet.add_row row
  end

  def write_row_for_company(user, sheet)
    row = []
    company = user.company

    write_rows_for_user user, row

    COMPANY_ROWS.each do |attribute|
      if COMPANY_TO_SINGLE_RELATIONS.keys.include? attribute
        if company.send(COMPANY_TO_SINGLE_RELATIONS[attribute]).nil?
          row << nil
        else
          row << company.send(COMPANY_TO_SINGLE_RELATIONS[attribute]).name
        end
      else
        row << (company[attribute].to_s.blank? ? nil : company[attribute])
      end
    end

    sheet.add_row row
  end

  def write_row_for_person(user, sheet)
    row = []
    person = user.person

    write_rows_for_user user, row

    PERSON_ROW.each do |attribute|
      row << (person[attribute].to_s.blank? ? nil : person[attribute])
    end

    sheet.add_row row
  end

  def write_row_for_opportunity(opportunity, sheet)
    row = []

    OPPORTUNITY_ROWS.each do |attribute|
      if attribute.eql? 'email'
        row << opportunity.user.email
      elsif attribute.eql? 'role_type'
        row << opportunity.user.role_name
      elsif attribute.eql? 'company_person_name'
        user = opportunity.user

        if user.role_id == User::ROLE_COMPANY
          row << user.company.company_name
        else
          row << user.full_name
        end
      elsif attribute.eql? 'number_of_applicants'
        row << opportunity.applications.count
      elsif attribute.eql? 'applicants_emails'
        row << opportunity.applied_users.map { |u| u.email }.join(',')
      elsif attribute.eql? 'selected_applicant_emails'
        row << opportunity.selected_students.map { |a| a.applied_user.email }.join(',')
      elsif OPPORTUNITY_TO_MANY_RELATIONS.include? attribute
        temp_row = []

        opportunity.send(attribute).each do |model|

app/views/administrators/_form.html.erb
 <%= form_for(@administrator) do |f| %>
    <%= render 'shared/error_messages', object: @administrator %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/administrators/_opportunities_table.html.erb
 <table class="table table-striped">
  <thead>
  <tr>
    <th>
      Oferente
    </th>
    <th>Correo oferente</th>
    <th>
      Nombre de la oferta
    </th>
    <th>
      Fecha de publicación
    </th>
    <th>
      # Aplicaciones
    </th>
    <th>
      Tiempo requerido
    </th>
    <th>
      Salario / Valor
    </th>
    <th colspan="5">Acciones</th>
  </tr>
  </thead>

  <tbody>
  <% @opportunities.each do |opportunity| %>
      <tr>
        <td>
          <% if opportunity.user.company.nil? %>
              <%= "#{opportunity.user.first_name} #{opportunity.user.last_name}"  %>
          <% else %>
              <%= opportunity.user.company.company_name  %>
          <% end %>
        </td>
        <td><%= opportunity.user.email %></td>
        <td>
          <%= opportunity.opportunity_title %>
        </td>
        <td>
          <%= opportunity.created_at.strftime('%d/%m/%Y') %>
        </td>
        <td>
          <%= "#{opportunity.applied_users.count} estudiantes" %>
        </td>
        <td>
          <%= opportunity_availability_friendly(opportunity) %>
        </td>
        <td>
          <% if opportunity.opportunity_cost.nil? %>
              <%= 'Se permite ofertar' %>
          <% else %>
              <%= opportunity.opportunity_cost %>
          <% end %>
        </td>

        <td><%= link_to 'Detalles', opportunity_path(opportunity), class: 'btn btn-default btn-studnet-details' %></td>
        <td><%= link_to 'Aplicantes', applicants_opportunity_path(opportunity), class: 'btn btn-studnet-details' %></td>
        <% unless opportunity.approved_state %>
            <td><%= link_to 'Aprobar', approve_opportunity_path(opportunity), method: :post, class: 'btn btn-default btn-studnet-details' %></td>
        <% end %>
        <td><%= link_to 'Borrar', opportunity, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-default btn-studnet-details' %></td>

        <td><%= link_to 'Editar', edit_opportunity_path(opportunity), class: 'btn btn-default btn-studnet-details' %></td>

        <% unless opportunity.closed %>
            <td><%= link_to 'Cerrar', close_opportunity_path(opportunity), data: { confirm: '¿Estás seguro? Esta acción es irreversible y una vez la cierra la oferta no será visible por los estudiantes' }, class: 'btn btn-default btn-studnet-details', method: :post %></td>
        <% end %>

      </tr>
  <% end %>
  </tbody>
</table>

app/views/administrators/edit.html.erb
 <h1>Editing Administrator</h1>

<%= render 'form' %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
 <h1>Listing Administrators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.name %></td>
        <td><%= link_to 'Show', administrator %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_administrator_path %>

app/views/administrators/new.html.erb
 <h1>New Administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/opportunities.html.erb
 <script>
    $(window).on('load',function(){
        $('#role').modal('show');
    });
</script>
<% if session[:excel]==true %>
    <div data-target="#role">
    </div>
    <!-- Modal -->
    <div class="modal fade" id="role" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
      <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title " id="exampleModalLongTitle">Aviso</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Pronto le estará llegando un correo con el Excel adjunto.
          </div>
          <div class="modal-footer">
            <button id="closePopup" type="button" class="pull-right btn btn-primary btn-studnet-basic"  data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
<%end %>
<script>
    $( "#closePopup" ).click(function()
    {   '<%= session["excel"]=false %>';
    });
</script>


<section class="studNet-wrapper">
  <div class="container">

    <div class="row">
      <div class="col-md-12">
        <div class="jumbotron text-center">
          <h2>Estadísticas</h2>

          <br/>

          <div class="row">
            <div class="col-md-3">
              <p class="no-margin"><strong>Estudiantes</strong></p>
              <p><%= @stats[:students] %></p>
            </div>

            <div class="col-md-3">
              <p class="no-margin"><strong>Personas</strong></p>
              <p><%= @stats[:people] %></p>
            </div>

            <div class="col-md-3">
              <p class="no-margin"><strong>Compañias</strong></p>
              <p><%= @stats[:companies] %></p>
            </div>

            <div class="col-md-3">
              <p class="no-margin"><strong>Ofertas activas</strong></p>
              <p><%= @stats[:active_offers] %></p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- List of all opportunities -->
    <div class="row">
      <div class="col-md-12">

        <h2>
          Lista de Ofertas
        </h2>

        <%= render 'administrators/opportunities_table' %>

      </div>
    </div>
    <!-- ./List of all opportunities -->

  </div>
</section>

app/views/administrators/pending_opportunities.html.erb
 <section class="studNet-wrapper">
  <div class="container">

    <!-- List of all opportunities -->
    <div class="row">
      <div class="col-md-12">

        <h1>
          Lista de Ofertas por aprobar
        </h1>

        <%= render 'administrators/opportunities_table' %>

      </div>
    </div>
    <!-- ./List of all opportunities -->

  </div>
</section>

app/views/administrators/show.html.erb
 <p>
  <strong>Name:</strong>
  <%= @administrator.name %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>