config/routes.rb
Rails.application.routes.draw do
  resources :notification_posts
  # =========================
  # Root
  # =========================
  root to: 'static_pages#index'

  # =========================
  # Devise
  # =========================
  devise_for :users, path: '', path_names: {
      sign_in: 'ingreso', sign_up: 'registro'
  }, controllers: {
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
  }

  devise_for :administrators, path: '', path_names: {
      sign_in: 'ingreso_admin'
  }
  # =========================
  # Resources
  # =========================
  resources :administrators do
    collection do
      get 'opportunities'
      get 'pending_opportunities'
      post 'download_excel'
    end
  end

  resources :companies, only: [:show, :index]
  resources :people, only: [:show, :index]
  resources :students, only: [:show, :index] do
    member do
      post 'delete_second_major'
    end
  end

  resources :users, except: [:new, :create, :show] do
    member do
      post 'build_learnt_language'
      post 'mark_as_selected'
      post 'rate_opportunity'
    end
  end

  resources :opportunities do
    member do
      get 'application_form'
      post 'apply'
      get 'applicants'
      post 'approve'
      post 'close'
      post 'acquire_information'
    end
    collection do
      get 'my_opportunities'
    end
  end

  # =========================
  # Controllers
  # =========================
  # get '/about', to: 'static_pages#about'
  get '/admin_panel', to: 'administrators#index'
  get '/company_pricing', to: 'static_pages#pricing'
  # get "/payment_page", :to => "companies#payment_page", :as => "payment_page"
  get "/payment_response_page", :to => "companies#payment_response_page", :as => "payment_response_page"
  post "/payment_confirmation_page", :to => "companies#payment_confirmation_page", :as => "payment_confirmation_page"

  # ============
  # Mailer
  # ============
  # match '/contacto', to: 'Contacts#new', via: :get
  # match '/contacto', to: 'Contacts#create', via: :post
end

app/models/opportunity.rb
 # == Schema Information
#
# Table name: opportunities
#
#  id                        :integer          not null, primary key
#  opportunity_type          :integer
#  opportunity_title         :string
#  activity_description      :text
#  skills_description        :text
#  other_majors              :boolean
#  question_for_student      :string
#  date_ini                  :date
#  opportunity_duration      :string
#  availability              :integer
#  cost_or_offer_option      :integer
#  opportunity_cost          :string
#  receive_portfolio         :boolean
#  number_of_students        :integer
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  user_id                   :integer
#  approved_state            :boolean          default(FALSE)
#  date_ini_type             :integer          default(0)
#  opportunity_duration_type :integer          default(0)
#  closed                    :boolean          default(FALSE)
#  description               :string
#  schedule                  :string
#  contract_type             :integer
#  city_id                   :integer
#  salary                    :text
#  compensatory_time_off     :integer
#  legal_benefits            :text
#

class Opportunity < ActiveRecord::Base

  #---------------------
  # Constants
  #---------------------
  TYPE_VIRTUAL = 0
  TYPE_ON_SITE = 1
  TYPE_PRACTICE = 2
  TYPE_FIRST_JOB = 3
  TYPE_SEASONAL = 4

  AVAILABILITY_FULL_TIME = 0
  AVAILABILITY_PART_TIME = 1
  AVAILABILITY_TWENTY_HOURS = 2

  OPTION_FOR_COST = 0
  OPTION_FOR_OFFER = 1

  TYPE_UNDEFINED = 0
  TYPE_AS_SOON_AS_POSSIBLE = 1
  TYPE_SET_DATE_INI = 2

  OPTION_FOR_DURATION_UNDEFINED = 0
  OPTION_FOR_DURATION_DEFINED = 1

  #---------------------
  # Associations
  #---------------------
  belongs_to :user
  belongs_to :city
  belongs_to :contract 

  has_many :students
  has_many :applications
  has_many :applied_users, through: :applications, class_name: 'User' # Students that applied to a company offer
  has_and_belongs_to_many :majors

  has_and_belongs_to_many :benefits


  accepts_nested_attributes_for :majors
  accepts_nested_attributes_for :benefits


  #---------------------
  # Validations
  #---------------------
  validates_presence_of :opportunity_type, :opportunity_title, :activity_description, :skills_description,
                        :availability, :number_of_students, :user_id, :date_ini_type, :opportunity_duration_type

  include PublicActivity::Model
  tracked




  #---------------------
  # Methods
  #---------------------
  def self.opportunities_for_student(student)
    major_ids = [student.major_id, student.second_major_id] + student.majors.map { |m| m.id }

    matching_opportunities = joins('INNER JOIN majors_opportunities ON majors_opportunities.opportunity_id = opportunities.id').
        where('(majors_opportunities.major_id IN (?) OR other_majors = ?) AND approved_state = ? AND closed = ?', major_ids, true, true, false)

    for_all_opportunities = where(other_majors: true, approved_state: true, closed: false)

    (matching_opportunities + for_all_opportunities).uniq
  end

  def self.approved
    where approved_state: true, closed: false
  end

  def self.pending_approval
    where approved_state: false
  end

  def approve
    self.approved_state = true
    self.save
  end

  def close
    self.closed = true
    self.save
  end

  def student_has_applied?(student)
    self.applied_users.include? student
  end

  def opportunity_type_description
    if self.opportunity_type == Opportunity::TYPE_VIRTUAL
      'Proyecto virtual'
    elsif self.opportunity_type == Opportunity::TYPE_ON_SITE
      'Empleo temporal'
    elsif self.opportunity_type == Opportunity::TYPE_PRACTICE
      'Práctica'
    elsif self.opportunity_type == Opportunity::TYPE_FIRST_JOB
      'Empleo'
    elsif self.opportunity_type == Opportunity::TYPE_SEASONAL
      'Trabajos express'
    end
  end

  def cost_or_offer_description
    if self.cost_or_offer_option == 0
      'Quiero poner un valor para el proyecto'
    else
      'Quiero escuchar ofertas de los estudiantes'
    end
  end

  def availability_description
    if self.availability == 0
      'Tiempo completo'
    elsif self.availability == 1
      'Medio tiempo'
    elsif self.availability == 2
      'Menos de 20 horas por semana'
    end
  end

  def duration_type_description
    if self.opportunity_duration_type == 0
      'Indefinida'
    else
      'Fijar duración'
    end
  end

  def selected_students
    self.applications.where selected: true
  end

  def date_ini_type_friendly
    if self.date_ini_type == Opportunity::Opportunity::TYPE_UNDEFINED
      'Indefinida'
    elsif self.date_ini_type == Opportunity::Opportunity::TYPE_AS_SOON_AS_POSSIBLE
      'Lo antes posible'
    elsif self.date_ini_type == Opportunity::Opportunity::TYPE_SET_DATE_INI
      'Fijar fecha'
    end
  end

  def get_application_for_user(user_id)
    applications_for_user = self.applications.where user_id: user_id

    if applications_for_user.count > 0
      applications_for_user.first
    else
      self.applications.build user_id: user_id
    end
  end

end

app/helpers/opportunities_helper.rb
 module OpportunitiesHelper

  def opportunity_majors_by_comma
    if @opportunity.other_majors
      'Todas las carreras'
    else
      @opportunity.majors.map{ |m| m.major_name }.join(', ')
    end
  end

  def opportunities_header_color
    if current_user.role_id == User::ROLE_STUDENT
      'students-show-view-header'
    elsif current_user.role_id == User::ROLE_COMPANY
      'companies-signup-header'
    elsif current_user.role_id == User::ROLE_PERSON
      'people-signup-header'
    end
  end

  def opportunities_tab_content_color
    if user_signed_in?
      if current_user.role_id == User::ROLE_COMPANY
        'company-tab-content'
      elsif current_user.role_id == User::ROLE_PERSON
        'person-tab-content'
      elsif current_user.role_id == User::ROLE_STUDENT
        'company-tab-content student-title-blue'
      end
    else
      ''
    end
  end

  # Helper method for building rails helper select from constants declared in the model
  def company_opportunity_select_type
    [
        ['Proyecto virtual', Opportunity::TYPE_VIRTUAL],
        ['Trabajos express', Opportunity::TYPE_SEASONAL],
        ['Empleo temporal', Opportunity::TYPE_ON_SITE],
        ['Empleo', Opportunity::TYPE_FIRST_JOB],
        ['Práctica', Opportunity::TYPE_PRACTICE]
    ]
  end

  def person_opportunity_select_type
    [
        ['Proyecto virtual', Opportunity::TYPE_VIRTUAL],
        ['Trabajos express', Opportunity::TYPE_SEASONAL],
        ['Empleo temporal', Opportunity::TYPE_ON_SITE],
        ['Empleo', Opportunity::TYPE_FIRST_JOB],
        ['Práctica', Opportunity::TYPE_PRACTICE]
    ]
  end

  # Helper method to display friendly name instead of select value
  def opportunity_type_friendly(opportunity)
    if opportunity.opportunity_type == Opportunity::TYPE_VIRTUAL
      'Proyecto virtual'
    elsif opportunity.opportunity_type == Opportunity::TYPE_ON_SITE
      'Empleo temporal'
    elsif opportunity.opportunity_type == Opportunity::TYPE_PRACTICE
      'Práctica'
    elsif opportunity.opportunity_type == Opportunity::TYPE_FIRST_JOB
      'Empleo'
    elsif opportunity.opportunity_type == Opportunity::TYPE_SEASONAL
      'Trabajos express'
    end
  end

  # Helper method for building rails helper select from constants declared in the model
  def opportunity_select_availability
    [
        ['Tiempo completo', Opportunity::AVAILABILITY_FULL_TIME],
        ['Medio tiempo', Opportunity::AVAILABILITY_PART_TIME],
        ['Menos de 20 horas por semana', Opportunity::AVAILABILITY_TWENTY_HOURS]
    ]
  end

  # Helper method to display friendly name instead of select value
  def opportunity_availability_friendly(opportunity)
    if opportunity.availability == 0
      'Tiempo completo'
    elsif opportunity.availability == 1
      'Medio tiempo'
    elsif opportunity.availability == 2
      'Menos de 20 horas por semana'
    end
  end

  # Helper method for building rails helper select from constants declared in the model
  def opportunity_select_cost_or_offer
    [
        ['Quiero poner un valor para el proyecto', Opportunity::OPTION_FOR_COST],
        ['Quiero escuchar ofertas de los estudiantes', Opportunity::OPTION_FOR_OFFER]
    ]
  end

  # Helper method to display friendly name instead of select value
  def opportunity_cost_or_offer_friendly(opportunity)
    if opportunity.cost_or_offer_option == 0
      'Quiero poner un valor para el proyecto'
    else
      'Quiero escuchar ofertas de los estudiantes'
    end
  end

  # Helper method for building rails helper select from constants declared in the model
  def opportunity_date_ini_type_select
    [
        ['Indefinida', Opportunity::TYPE_UNDEFINED],
        ['Lo antes posible', Opportunity::TYPE_AS_SOON_AS_POSSIBLE],
        ['Fijar fecha', Opportunity::TYPE_SET_DATE_INI]
    ]
  end

   # Helper method for building rails helper select from constants declared in the model
  def opportunity_contract_type_select
    [
        ['Contrato a Termino Fijo.', 1],
        ['Contrato a Termino Indefinido.', 2],
        ['Contrato de Obra o Labor.', 3],
        ['Contrato de Aprendizaje.', 4],
        ['Contrato Civil por Prestación de Servicios', 5]
    ]
  end

  def opportunity_compensatory_time_off_select
     [
        ['Fin de Semana', 1],
        ['Sabados', 2],
        ['Domingos', 3],
        ['Un día entre semana', 4]
    ]
  end

  # Helper method to display friendly name instead of select value
  def opportunity_date_ini_type_friendly(opportunity)
    if opportunity.date_ini_type == 0
      'Indefinido'
    elsif opportunity.date_ini_type == 1
      'Lo antes posible'
    else
      'Fijar fecha'
    end
  end

  # Helper method for building rails helper select from constants declared in the model
  def opportunity_duration_type_select
    [
        ['Indefinida', Opportunity::OPTION_FOR_DURATION_UNDEFINED],
        ['Fijar duración', Opportunity::OPTION_FOR_DURATION_DEFINED]
    ]
  end

  # Helper method to display friendly name instead of select value
  def opportunity_duration_type_friendly(opportunity)
    if opportunity.opportunity_duration_type == 0
      'Indefinida'
    else
      'Fijar duración'
    end
  end

  def opportunity_salary_friendly(opportunity)
    if opportunity.cost_or_offer_option == Opportunity::OPTION_FOR_OFFER
      'Recibo ofertas'
    else
      opportunity.opportunity_cost
    end
  end

end

app/views/opportunities/_rating_modal.html.erb
 <div class="modal fade" id="<%= "application-#{application.id}" %>" tabindex="-1" role="dialog" aria-labelledby="<%= "application-#{application.id}" %>Label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_tag rate_opportunity_user_path(applicant) do %>
          <%= hidden_field_tag :opportunity, @opportunity.id %>

          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="<%= "application-#{application.id}" %>Label">Calificación de <%= applicant.full_name %></h4>
          </div>
          <div class="modal-body">
            <p>Seleccione la califiación a asignar a <%= applicant.full_name %>.</p>
            <%= select_tag :rating, options_for_select([1, 2, 3, 4, 5], { prompt: 'Por favor seleccione la opción' }), class: 'form-control input-width' %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            <%= submit_tag 'Calificar', class: 'btn btn-default btn-studnet-details' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/opportunities/edit.html.erb
  <section class="devise-wrapper">
  <div class="<%= (current_user.role_id == User::ROLE_COMPANY ? 'companies-signup-header' : 'people-signup-header') if user_signed_in? %> margin-bot-40">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>
            Editar oferta
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="studNet-wrapper student-tab-wrapper padding-bot-40">
  <div class="container">

    <div class="row">
      <div class="col-md-10 col-md-offset-1 student-tab-content <%= opportunities_tab_content_color %>">

        <div class="row">
          <div class="col-md-6">
            <h3>
              Editar oferta
            </h3>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <%= render 'form' %>
          </div>
        </div>

      </div>
    </div>

  </div>
</section>

app/views/opportunities/my_opportunities.html.erb
 <script>
    $(window).on('load',function(){
        $('#company').modal('show');
    });
</script>
<% if session[:myOp]==true %>
    <div data-target="#company">
    </div>
    <!-- Modal -->
    <div class="modal fade" id="company" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
      <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title " id="exampleModalLongTitle">Información</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Aquí encontrarás la información correspondiente a tus ofertas
          </div>
          <div class="modal-footer">
            <button id="closePopup" type="button" class="pull-right btn btn-primary btn-studnet-basic"  data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
<%end %>
<script>
    $( "#closePopup" ).click(function()
    {   '<%= session["myOp"]=false %>';
    });
</script>
<section class="devise-wrapper">
  <div class="<%= opportunities_header_color %> margin-bot-20">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>
            Mis Ofertas
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="studNet-wrapper padding-bot-40">
  <div class="container">

    <% if @user_role.role_id == User::ROLE_COMPANY || @user_role.role_id == User::ROLE_PERSON %>
        <!-- My Opportunities for Companies/People -->
        <div class="row">
          <div class="col-md-12">

            <h1>
              Mis Ofertas
            </h1>

            <table class="table table-striped my-opportunities-table">
              <thead>
              <tr>
                <th>
                  Nombre de la oferta
                </th>
                <th>
                  Tipo de proyecto
                </th>
                <th>
                  # Aplicaciones
                </th>
                <th>
                  Estado
                </th>
                <th>
                  Fecha de publicación
                </th>
                <th colspan="4">Acciones</th>
              </tr>
              </thead>

              <tbody>
              <% @my_opportunities.each do |opportunity| %>
                  <tr>
                    <td>
                      <%= opportunity.opportunity_title %>
                    </td>
                    <td>
                      <%= opportunity_type_friendly(opportunity)  %>
                    </td>
                    <td>
                      <%= "#{opportunity.applied_users.count} estudiantes" %>
                    </td>
                    <td>
                      <%= opportunity.approved_state ? 'Aprobada' : 'Por aprobar' %> |
                      <%= opportunity.closed ? 'Cerrada' : 'Abierta' %>
                    </td>
                    <td>
                      <%= opportunity.created_at.strftime('%d/%m/%Y') %>
                    </td>

                    <td><%= link_to 'Detalles', opportunity_path(opportunity), class: 'btn btn-studnet-details' %></td>
                    <td><%= link_to 'Aplicantes', applicants_opportunity_path(opportunity), class: 'btn btn-studnet-details' %></td>

                    <% unless opportunity.approved_state %>
                        <td><%= link_to 'Editar', edit_opportunity_path(opportunity), class: 'btn btn-studnet-details' %></td>
                    <% end %>

                    <% unless opportunity.closed %>
                        <td><%= link_to 'Cerrar', close_opportunity_path(opportunity), data: { confirm: '¿Estás seguro? Esta acción es irreversible y una vez se cierre la oferta, esta no será visible para los estudiantes' }, class: 'btn btn-studnet-details', method: :post %></td>
                    <% end %>
                  </tr>
              <% end %>
              </tbody>
            </table>

          </div>
        </div>
        <!-- ./My Opportunities for Companies/People -->
    <% elsif @user_role.role_id == User::ROLE_STUDENT %>
        <!-- My Opportunities for Students -->
        <div class="row">
          <div class="col-md-12">

            <h1>
              Mis Ofertas
            </h1>

            <table class="table table-striped">
              <thead>
              <tr>
                <th>
                  Tipo de proyecto
                </th>
                <th>
                  Nombre de la oferta
                </th>
                <th>
                  Fecha de publicación
                </th>
                <th>
                  Duración
                </th>
                <th>
                  Tiempo requerido
                </th>
                <th>
                  Salario / Valor
                </th>
                <th colspan="5">Acciones</th>
              </tr>
              </thead>

              <tbody>
              <% @student_opportunities.each do |opportunity| %>
                  <tr>
                    <td>
                      <%= opportunity_type_friendly(opportunity) %>.
                    </td>
                    <td>
                      <%= opportunity.opportunity_title %>
                    </td>
                    <td>
                      <%= opportunity.created_at.strftime('%d/%m/%Y') %>
                    </td>
                    <td>
                      <%= opportunity.opportunity_duration %>
                    </td>
                    <td>
                      <%= opportunity_availability_friendly(opportunity) %>
                    </td>
                    <td>
                      <%= opportunity_salary_friendly(opportunity) %>
                    </td>
                    <td><%= link_to 'Detalles', opportunity, class: 'btn btn-studnet-details' %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>

          </div>
        </div>
        <!-- ./My Opportunities for Students -->
    <% end %>

    <!-- My Opportunities Actions -->
    <% if (@user_role.role_id == User::ROLE_COMPANY || @user_role.role_id == User::ROLE_PERSON) && !current_user.profile_incomplete? %>
        <div class="row">
          <div class="col-md-12 text-center">
            <%= link_to 'Crear oferta', new_opportunity_path, class: 'btn btn-primary btn-studnet-basic' %>
          </div>
        </div>
    <% elsif @user_role.role_id == User::ROLE_STUDENT %>
        <div class="row">
          <div class="col-md-12 text-center">
            <%= link_to 'Ver más ofertas', opportunities_path, class: 'btn btn-primary btn-studnet-basic' %>
          </div>
        </div>
    <% end %>
    <!-- ./My Opportunities Actions -->
  </div>
</section>

app/views/opportunities/new.html.erb
 <section class="devise-wrapper">
  <div class="<%= current_user.role_id == User::ROLE_COMPANY ? 'companies-signup-header' : 'people-signup-header' %> margin-bot-40">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>
            Crear oferta
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="studNet-wrapper student-tab-wrapper padding-bot-40">
  <div class="container">

    <div class="row">
      <div class="col-md-10 col-md-offset-1 student-tab-content <%= current_user.role_id == User::ROLE_COMPANY ? 'company-tab-content' : 'person-tab-content' %> ">

        <div class="row">
          <div class="col-md-6">
            <h3>
              Crear nueva oferta
            </h3>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <%= render 'form' %>
          </div>
        </div>

      </div>
    </div>

  </div>
</section>

app/views/opportunities/show.html.erb
 <section class="devise-wrapper">
  <div class="students-show-view-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p>
            Ver oferta
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="studNet-wrapper student-tab-wrapper opportunity-wrapper padding-bot-40">
  <div class="container">

    <div class="row">
      <div class="col-md-10 col-md-offset-1 student-tab-content <%= opportunities_tab_content_color %>">

        <div class="row">
          <div class="col-md-6 margin-bot-20">
            <h3>
              <%= @opportunity.opportunity_title %>
            </h3>

          </div>
        </div>


        <div class="row">
          <div class="col-md-6">

            <div class="row">
              <div class="col-md-12">
                <p>
                  <strong>
                    Tipo de oferta:
                  </strong>
                  <br>
                  <%= opportunity_type_friendly(@opportunity) %>
                </p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <p>
                  <strong>
                    Actividades a realizar:
                  </strong>
                  <br>
                  <%= @opportunity.activity_description %>
                </p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <p>
                  <strong>
                    Habilidades y conocimientos requeridos:
                  </strong>
                  <br>
                  <%= @opportunity.skills_description %>
                </p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <p>
                  <strong>
                    Carreras:
                  </strong>
                  <br>
                  <%= opportunity_majors_by_comma %>
                </p>
              </div>
            </div>

          </div>

          <div class="col-md-6">

            <div class="row">
              <div class="col-md-12">
                <p>
                  <% if @opportunity.date_ini_type.to_i == 2 %>
                      <strong>
                        Fecha de inicio del trabajo / proyecto:
                      </strong>
                      <br>
                      <%= @opportunity.date_ini.strftime('%Y/%m/%d ') %>
                  <% else %>
                      <strong>
                        Fecha de inicio del trabajo / proyecto:
                      </strong>
                      <br>
                      <%= opportunity_date_ini_type_friendly(@opportunity) %>
                  <% end %>
                </p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <p>
                  <% if @opportunity.opportunity_duration_type.to_i == 1 %>
                      <strong>
                        Duración del trabajo / proyecto:
                      </strong>
                      <br>
                      <%= @opportunity.opportunity_duration %>
                  <% else %>
                      <strong>
                        Duración del trabajo / proyecto:
                      </strong>
                      <br>
                      <%= opportunity_duration_type_friendly(@opportunity) %>
                  <% end %>
                </p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <p>
                  <strong>
                    Tiempo requerido del estudiante:
                  </strong>
                  <br>
                  <%= opportunity_availability_friendly(@opportunity) %>
                </p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <p>
                  <% if @opportunity.cost_or_offer_option == Opportunity::OPTION_FOR_OFFER %>
                      <strong>
                        Salario / valor del proyecto:
                      </strong>
                      <small>(Para proyectos virtuales, recuerda que studNet cobra un 10% más IVA de comisión sobre este valor. Adicionalmente, si el proyecto fue publicado por una empresa, esta podrá retener hasta un 12% sobre este valor por concepto de retención en la fuente y retención de ICA)</small>
                      <br>
                      <%= opportunity_cost_or_offer_friendly(@opportunity) %>
                  <% else %>
                      <strong>
                        Salario / valor del proyecto:
                      </strong>
                      <small>(Para proyectos virtuales, recuerda que studNet cobra un 10% más IVA de comisión sobre este valor. Adicionalmente, si el proyecto fue publicado por una empresa, esta podrá retener hasta un 12% sobre este valor por concepto de retención en la fuente y retención de ICA)</small>
                      <br>
                      <%= @opportunity.opportunity_cost %>
                  <% end %>
                </p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <p>
                  <strong>
                    Número de estudiantes:
                  </strong>
                  <br>
                  <%= @opportunity.number_of_students %>
                </p>
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center student-actions-wrapper">
        <% unless administrator_signed_in?  %>
            <% if @user_role.role_id == User::ROLE_STUDENT %>
                <% if @user_role.profile_incomplete? %>
                    <p>Debes completar tu perfil para poder aplicar a la oferta.</p>
                    <%= link_to 'Terminar perfil', edit_user_path(@user_role), class: 'btn btn-primary btn-studnet-basic' %>
                <% else %>
                    <% if @opportunity.student_has_applied?(current_user) %>
                        <%= link_to 'Ya aplicaste a la oferta', my_opportunities_opportunities_path, class: 'btn btn-primary btn-studnet-basic' %>
                    <% else %>
                        <%= link_to 'Aplicar', application_form_opportunity_path(@opportunity), class: 'btn btn-primary btn-studnet-basic' %>
                    <% end %>
                <% end %>

                <%= link_to 'Ver ofertas', opportunities_path, class: 'btn btn-primary btn-studnet-basic' %>
            <% elsif @user_role.role_id == User::ROLE_COMPANY || @user_role.role_id == User::ROLE_PERSON %>
                <%= link_to 'Mis ofertas', my_opportunities_opportunities_path, class: 'btn btn-primary btn-studnet-basic' %>

                <%#= link_to 'Editar', edit_opportunity_path(@opportunity.id), class: 'btn btn-primary btn-studnet-basic' %>

                <%#= link_to 'Archivar', '#',class: 'btn btn-primary btn-studNet' %>
            <% end %>
        <% end %>
      </div>
    </div>

  </div>
</section>